### PR TITLE
Add an OEP-2 compliant openedx.yaml file

### PR DESCRIPTION
**Pull request by cpennington**
This adds an `openedx.yaml` file, as described by OEP-2:
http://open-edx-proposals.readthedocs.io/en/latest/oeps/oep-0002.html

The data in this file was transformed from the contents of
edx/repo-tools-data:repos.yaml

### CODE REVIEW

**Comment by cpennington** [comment]
@edx/devops: I'm marking this repo as yours.

**Comment by jibsheet** [comment]
@cpennington I think @benpatterson and his teams own this?

**Comment by cpennington** [comment]
@jibsheet: Hrm. It was marked for you guys in @e0d's big spreadsheet-o-repos.

**Comment by jibsheet** [comment]
@cpennington hmm, ok.  Let's see what Ben says.  He and his teams have done most of the work on these aside from the work to put them onto the sandboxes which we did because it involved that complicated jenkins job.

**Comment by benpatterson** [comment]
tagging it with tools and putting edx/testeng makes sense to me. (i wish we had edx/tools btw, which would make more sense in this case...at least to me.)

**Comment by jibsheet** [comment]
Annoyingly, it doesn't look like we can just make a tools group and put testeng as a member, we'd have to maintain the lists together.  That can happen if you prefer, ITSUPPORT is the right JIRA queue.

**Comment by cpennington** [comment]
It appears that we can rename the team (although it won't update old mentions).

I'll change the owner on this repo.

**Pull request merged**
